#!/usr/bin/env bash
# Display subdomain information

# shellcheck disable=SC2086

dig_domain() {
    line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]; then
    subdomains=("www" "lb-01" "web-01" "web-02")
    for sub in "${subdomains[@]}"; do
        dig_domain "$1" "$sub"
    done
elif [ "$#" == 2 ]; then
    dig_domain "$1" "$2"
fi
