#!/usr/bin/env bash
# A script that installs and configures Nginx on a server

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
sudo service nginx restart

