#!/usr/bin/env bash
# A script that configures Nginx server to redirect to another page

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html

cat <<EOL | sudo tee /etc/nginx/sites-enabled/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;

    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location /redirect_me {
        return 301 https://twitter.com/;
    }
}
EOL

sudo service nginx restart

