#!/usr/bin/env bash
# configures a server to overcome restriction of Nginx installation from listening on port 80

sudo ln -sf /etc/nginx/sites-available/default  /etc/nginx/sites-enabled/default
service nginx restart
