#!/usr/bin/env bash
# Displays "To infinity and beyond" indfinitely

echo $$ > /var/run/myscript.pid

while true
do
   echo "To infinity and beyond"
   sleep 2

   trap 'echo "Y U no love me?!"' SIGTERM
   trap 'echo "I hate the kill command"; rm /var/run/myscript.pid; exit' SIGTERM
   trap 'rm /var/run/myscript.pid; exit' SIGQUIT

done
