#!/usr/bin/env bash
#This script is displaying "Best school" 10 times

n=1

while [ $n -le 10 ]
do

   if [[ $n -ne 4  && $n -ne 8 ]]
   then
      echo "Best School"

   elif [ $n -eq 8 ]
   then
      echo "good luck"

   else [ $n -eq 4 ]

      echo "bad luck"
   fi

   ((n++))

done
