#!/usr/bin/env bash
#Configures an Ubuntu server with new localhost and facebook Host

cp /etc/hosts ~/new_hosts

echo "127.0.0.2		localhost" > ~/new_hosts
echo "8.8.8.8		facebook.com" >> ~/new_hosts

cp -f ~/new_hosts /etc/hosts
